### ISSUE TITLE
[BUG]stackblur-go may override source image to be blurred

### ISSUE THREAD

**Issue by hzl2928963** [esimov/stackblur-go#1]
Hi, once I use your stackblur-go to process images in batch, then I found when I call func "Process", the source image I passed in as parameter "src", it may be override in some cases. Intuitively, source image should be read-only, isn't it ?

**Comment by esimov** [comment]
The source image should not be changed. It might happen in case the output has the exact same name as the source image. Can you detail or give a sample code how you are using the batch command?
