### ISSUE TITLE
Why the channel?

### ISSUE THREAD

**Issue by tpjg** [esimov/stackblur-go#2]
Not really an issue, just a question: what is the purpose of the ```done chan struct{}``` channel? Also in the example program you just call the function and time it without using the channel. IMHO if an explication would need some sort of notification it is probably better implemented outside of the Process function.

**Comment by esimov** [comment]
The usage of channel has a single purpose: to notify the channel consumer if the generation has been finished, but you are right that it would be much cleaner if we can eliminate or at least move out from the core implementation. I will refactor the code.

**Comment by esimov** [comment]
@tpjg I refactored the code, also updated the documentation. I have eliminated the use of the channel from method invocation, so pretty much cleaned up the code. Honestly i don't even know what motivated me to use the channel operator in the function call.

**Comment by esimov** [comment]
@tpjg I refactored the code and also updated the documentation. I have eliminated the channel from method invocation, so the code is pretty much cleaned now. Honestly i don't even know what was the reason to use the channel operator in the function call.
