### ISSUE TITLE
Panic - Unknown format

### ISSUE THREAD

**Issue by pedro4286** [esimov/stackblur-go#3]
I ran it with 2 pngs and I got main.go : 44  +0x6ae
The command was cli.exe -in Wallpaper.png -our Blur.png -radius 10

**Comment by pedro4286** [comment]
I haven’t looked until now but a correction is from “our” to “output”

**Comment by pedro4286** [comment]
Another correction is from output to out, I can’t believe I keep making these mistakes lol

**Comment by pedro4286** [comment]
So it was an error on my end with an incorrectly encoded file, I apologise for your time

**Comment by esimov** [comment]
No problem, then i will close this ticket.
