### ISSUE TITLE
Panic on grayscale images

### ISSUE THREAD

**Issue by k-danil** [esimov/stackblur-go#6]
Good day!

I got repeatable panic on grayscale images:
```
./main -in 511be36c3d8721964318518f9a2bb691.jpeg -out out.jpeg -radius 10
panic: runtime error: index out of range [786432] with length 786432

goroutine 1 [running]:
github.com/esimov/stackblur-go.toNRGBA({0x100526f60, 0x140000c2140})
	/Users/danil/blur/stackblur-go/stackblur.go:420 +0x3d0
github.com/esimov/stackblur-go.Process({0x100526f60, 0x140000c2140}, 0xa)
	/Users/danil/blur/stackblur-go/stackblur.go:83 +0xa4
main.main()
	/Users/danil/blur/stackblur-go/cmd/main.go:71 +0x1f8
```

Changing https://github.com/esimov/stackblur-go/blob/d3c03d1cf5a4fbe35f8411d51a81fcaaed3fa8ae/stackblur.go#L426 to simple `si++` fixes the issue. 
Please take a look.

Example image:
  ![511be36c3d8721964318518f9a2bb691](https://github.com/esimov/stackblur-go/assets/33830890/09bad8e7-44cf-47f0-a8bf-71412cc634e4)

**Comment by esimov** [comment]
Thank you for letting me know. The issue should be fixed now.

**Comment by k-danil** [comment]
Good day!

Fixed. Thanks for quick response.
